version: "3.8"
services:
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Zanoni25175"
    volumes:
      - db_data:/var/opt/mssql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      MSSQL_SERVER: db
      MSSQL_DATABASE: RGodoyNew
      MSSQL_USER: sa
      MSSQL_PASSWORD: Zanoni25175
      SECRET_KEY: "your_secret_key"
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    depends_on:
      - db

  gateway:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend

volumes:
  db_data: